# import userbot by skyzo

from time import sleep
from userbot.events import register


@register(outgoing=True, pattern='^.epep(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**Sial Ada Anak Epep😨**")
    sleep(1)
    await typew.edit("**Sekuat Apapun Aku😰**")
    sleep(1)
    await typew.edit("**Jika Ada Anak Epep😨**")
    sleep(1)
    await typew.edit("**Aku Harus Lari🏃🏻**")
    sleep(1)
    await typew.edit("**Lari Cukkk Ada Anak Epep🏃🏻**")
    sleep(1)
    await typew.edit("**Argghh Bangkeee!🏃🏻**")
    sleep(1)
    await typew.edit("**Lari Sekencang-Kencangnya🤸🏻**")
    sleep(1)
    await typew.edit("**Karena Kita Sedang🤾🏻**")
    sleep(1)
    await typew.edit("**Menghadapi Anak Epep🤸🏻**")
    sleep(1)
    await typew.edit("**Epep,Wibu,Mikey,Hengker🏃🏻**")
    sleep(1)
    await typew.edit("**Arghhhhhhh**")
    sleep(1)
    await typew.edit("**Lari Sekarang**")
    sleep(1)
    await typew.edit("**Mainnya Epep🤾🏻**")
    sleep(1)
    await typew.edit("**Dasar Anak Epep😨**")
    sleep(1)
    await typew.edit("**Maaf Anak Epep🤼‍♂️**")
    sleep(1)
    await typew.edit("**Aku Tidak Akan🤾🏻**")
    sleep(1)
    await typew.edit("**Mengulanginya Lagi🏃🏻**")
    sleep(1)
    await typew.edit("**Tapi Bo'ong🤾🏻**")
    sleep(1)
    await typew.edit("**Dasar Anak Epep, Hobby Ngatain Tapi Di Katain Balik Koar-Koar🤣😂**")
