# import userbot by apis

from time import sleep
from userbot import ALIVE_NAME, CMD_HELP
from userbot.events import register


@register(outgoing=True, pattern='^.wibuu(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Kata Emak`")
    sleep(2)
    await typew.edit("`Kalo Ketemu Wibuu`")
    sleep(3)
    await typew.edit("`Harus Lari Sekenceng Mungkin🏃🏻`")
    sleep(3)
    await typew.edit("`ㅤㅤㅤㅤㅤㅤㅤㅤㅤ🏃🏻          🏂`")
    await typew.edit("`ㅤㅤㅤㅤㅤㅤㅤㅤ🏃🏻💨        🏂`")
    await typew.edit("`ㅤㅤㅤㅤㅤㅤㅤ🏃🏻💨        🏂ㅤ`")
    await typew.edit("`ㅤㅤㅤㅤㅤㅤ🏃🏻💨ㅤㅤ    🏂   `")
    await typew.edit("`ㅤㅤㅤㅤㅤ🏃🏻💨ㅤㅤ        🏂ㅤ`")
    await typew.edit("`ㅤㅤㅤㅤ🏃🏻💨  sini lu ajg   🏂ㅤ`")
    await typew.edit("`ㅤㅤㅤ🏃🏻💨ㅤㅤㅤㅤㅤ       🏂`")
    await typew.edit("`ㅤㅤ🏃🏻💨ㅤㅤㅤㅤㅤ       🏂ㅤ`")
    await typew.edit("`ㅤ🏃🏻💨ㅤㅤwibuㅤ      🏂ㅤㅤㅤㅤ`")
    await typew.edit("`🏃🏻💨ㅤㅤㅤㅤㅤㅤ    🏂ㅤㅤ`")
# create by skyzo

    await pong.edit("__Loading Kegantengan Skyzo😎.....__")
    await pong.edit("**0% ▒▒▒▒▒▒▒▒▒▒**")
    await pong.edit("**20% ██▒▒▒▒▒▒▒▒**")
    await pong.edit("**40% ████▒▒▒▒▒▒**")
    await pong.edit("**60% ██████▒▒▒▒**")
    await pong.edit("**80% ████████▒▒**")
    await pong.edit("**100% ██████████**")
    sleep(2)
    await typew.edit("**Skyzo Ganteng 1000%😎**")


@register(outgoing=True, pattern='^.wibu(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(0.07)
    await typew.edit("**Sial Ada Wibu😨**")
    sleep(0.07)
    await typew.edit("**Sekuat Apapun Aku😭**")
    sleep(0.07)
    await typew.edit("**Jika Ada Wibu😨**")
    sleep(0.07)
    await typew.edit("**Aku Harus Lari🏃🏻**")
    sleep(0.07)
    await typew.edit("**Lari Cukkk Ada Wibuuu🏃🏻**")
    sleep(0.07)
    await typew.edit("**Argghh Bangkeee!🏃🏻**")
    sleep(0.07)
    await typew.edit("**Lari Sekencang-Kencangnya🤸🏻**")
    sleep(0.07)
    await typew.edit("**Karena Kita Sedang🤾🏻**")
    sleep(0.07)
    await typew.edit("**Menghadapi Ras Terkuat🤸🏻**")
    sleep(0.07)
    await typew.edit("**Yang Ada Di Dunia🏃🏻**")
    sleep(0.07)
    await typew.edit("**Wibuuuu🪂**")
    sleep(0.07)
    await typew.edit("**Arghhhhhhh🧗🏻**")
    sleep(0.07)
    await typew.edit("**Istrinya Kartun🤾🏻**")
    sleep(0.07)
    await typew.edit("**Dasar Wibu😨**")
    sleep(0.07)
    await typew.edit("**Maaf Wibu🤼‍♂️**")
    sleep(0.07)
    await typew.edit("**Aku Tidak Akan🤾🏻**")
    sleep(0.07)
    await typew.edit("**Mengulanginya Lagi🏃🏻**")
    sleep(0.07)
    await typew.edit("**Tapi Bo'ong🤾🏻**")
    sleep(0.07)
    await typew.edit("**Dasar Wibu, Istri Kartun🪂**")

@register(outgoing=True, pattern='^.wibbu(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**WI WIII WIIII WIIII.....**")
    sleep(1)
    await typew.edit("__WIBUUU ANJIRRRRR!....__")
    sleep(1)
    await typew.edit("`🏃                        🏂`")
    await typew.edit("`🏃                       🏂`")
    await typew.edit("`🏃                      🏂`")
    await typew.edit("`🏃                     🏂`")
    await typew.edit("`🏃   `LARII`          🏂`")
    await typew.edit("`🏃                   🏂`")
    await typew.edit("`🏃                  🏂`")
    await typew.edit("`🏃                 🏂`")
    await typew.edit("`🏃                🏂`")
    await typew.edit("`🏃               🏂`")
    await typew.edit("`🏃              🏂`")
    await typew.edit("`🏃             🏂`")
    await typew.edit("`🏃            🏂`")
    await typew.edit("`🏃           🏂`")
    await typew.edit("`🏃..Tolong..🏂`")
    await typew.edit("`🏃           🏂`")
    await typew.edit("`🏃            🏂`")
    await typew.edit("`🏃             🏂`")
    await typew.edit("`🏃              🏂`")
    await typew.edit("`🏃               🏂`")
    await typew.edit("`🏃                🏂`")
    await typew.edit("`🏃                 🏂`")
    await typew.edit("`🏃                  🏂`")
    await typew.edit("`🏃                   🏂`")
    await typew.edit("`🏃                    🏂`")
    await typew.edit("`🏃                     🏂`")
    await typew.edit("`🏃  Huh-Huh-Huh       🏂`")
    await typew.edit("`🏃                   🏂`")
    await typew.edit("`🏃                  🏂`")
    await typew.edit("`🏃                 🏂`")
    await typew.edit("`🏃                🏂`")
    await typew.edit("`🏃               🏂`")
    await typew.edit("`🏃              🏂`")
    await typew.edit("`🏃             🏂`")
    await typew.edit("`🏃            🏂`")
    await typew.edit("`🏃           🏂`")
    await typew.edit("`🏃          🏂`")
    await typew.edit("`🏃         🏂`")
    await typew.edit("__KOK MAKIN DEKET SI WIBU__")
    sleep(1)
    await typew.edit("`🏃       🏂`")
    await typew.edit("`🏃      🏂`")
    await typew.edit("`🏃     🏂`")
    await typew.edit("`🏃    🏂`")
    await typew.edit("**Untung Ngga Kena Njir**")
    sleep(1)
    await typew.edit("😟")
    sleep(2)
    await typew.edit("**Kasian Si Wibu Wokwokwok**")
    

CMD_HELP.update(
    {
        "random": "**✘ Plugin :** `wibu`\
        \n\n  •  **Perintah :** `.wibu`\
        \n  •  **Function : **Untuk melihat sesuatu yang menarik\
        \n  •  **Function : **Lari Cuk Ada Wibuuu Arghhhh**\
        \n  ** Harap chat developer king @SkyzoSaja Jika ingin mengidekan sesuatu yang menarik **\
        \n\n  ** Perintah kosong **\
        \n  ** Harap chat developer king @SkyzoSaja Jika ingin mengidekan sesuatu yang menarik **\
    "
    }
)
