# import userbot by apis

from time import sleep
from userbot import ALIVE_NAME, CMD_HELP
from userbot.events import register


@register(outgoing=True, pattern='^.wibuu(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Kata Emak`")
    sleep(2)
    await typew.edit("`Kalo Ketemu Wibuu`")
    sleep(3)
    await typew.edit("`Harus Lari Sekenceng Mungkin🏃🏻`")
    sleep(3)
    await typew.edit("`🏃🏻.......................🏃`")
    await typew.edit("`🏃🏻.....................🏃`")
    await typew.edit("`🏃🏻...................🏃`")
    await typew.edit("`🏃🏻.................🚶`")
    await typew.edit("`🏃🏻...............🏃`")
    await typew.edit("`🏃🏻..Sini lu ajg..🚶`")
    await typew.edit("`🏃🏻..............🏃`")
    await typew.edit("`🏃🏻....Ga Ah...🏃`")
    await typew.edit("`🏃🏻...wibu...🏃`")
    await typew.edit("`🏃🏻..Tamat..🏃`")
# create by skyzo



@register(outgoing=True, pattern='^.wibu(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(0.07)
    await typew.edit("**Sial Ada Wibu😨**")
    sleep(0.07)
    await typew.edit("**Sekuat Apapun Aku😭**")
    sleep(0.07)
    await typew.edit("**Jika Ada Wibu😨**")
    sleep(0.07)
    await typew.edit("**Aku Harus Lari🏃🏻**")
    sleep(0.07)
    await typew.edit("**Lari Cukkk Ada Wibuuu🏃🏻**")
    sleep(0.07)
    await typew.edit("**Argghh Bangkeee!🏃🏻**")
    sleep(0.07)
    await typew.edit("**Lari Sekencang-Kencangnya🤸🏻**")
    sleep(0.07)
    await typew.edit("**Karena Kita Sedang🤾🏻**")
    sleep(0.07)
    await typew.edit("**Menghadapi Ras Terkuat🤸🏻**")
    sleep(0.07)
    await typew.edit("**Yang Ada Di Dunia🏃🏻**")
    sleep(0.07)
    await typew.edit("**Wibuuuu🪂**")
    sleep(0.07)
    await typew.edit("**Arghhhhhhh🧗🏻**")
    sleep(0.07)
    await typew.edit("**Istrinya Kartun🤾🏻**")
    sleep(0.07)
    await typew.edit("**Dasar Wibu😨**")
    sleep(0.07)
    await typew.edit("**Maaf Wibu🤼‍♂️**")
    sleep(0.07)
    await typew.edit("**Aku Tidak Akan🤾🏻**")
    sleep(0.07)
    await typew.edit("**Mengulanginya Lagi🏃🏻**")
    sleep(0.07)
    await typew.edit("**Tapi Bo'ong🤾🏻**")
    sleep(0.07)
    await typew.edit("**Dasar Wibu, Istri Kartun🪂**")

@register(outgoing=True, pattern='^.wibbu(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**WI WIII WIIII**")
    await typew.edit("`🏃.....Wibu Anjir.......🏃`")
    await typew.edit("`🏃....................🏃`")
    await typew.edit("`🏃..................🏃`")
    await typew.edit("`🏃.....`LARII`....🏃`")
    await typew.edit("`🏃..............🏃`")
    await typew.edit("`🏃.............🏃`")
    await typew.edit("`🏃..Anjing...🏃`")
    await typew.edit("`🏃.........🏃`")
    await typew.edit("`🏃..Wiba..🏃`")
    await typew.edit("`🏃...Wibu...🏃`")
    await typew.edit("`🏃....Cringe..🏃`")
    await typew.edit("`🏃....Tolol.....🏃`")
    await typew.edit("`🏃............🏃`")
    await typew.edit("`🏃..Tolong..🏃`")
    await typew.edit("`🏃...........🏃`")
    await typew.edit("`🏃............🏃`")
    await typew.edit("`🏃.............🏃`")
    await typew.edit("`🏃....Watashi...🏃`")
    await typew.edit("`🏃.....Kejar.....🏃`")
    await typew.edit("`🏃.....Sampai.....🏃`")
    await typew.edit("`🏃.....Dapat.......🏃`")
    await typew.edit("`🏃..................🏃`")
    await typew.edit("`🏃......Anjir........🏃`")
    await typew.edit("`🏃....................🏃`")
    await typew.edit("`🏃.....................🏃`")
    await typew.edit("`🏃..Huh-Huh-Huh.......🏃`")
    await typew.edit("`🏃...................🏃`")
    await typew.edit("`🏃..................🏃`")
    await typew.edit("`🏃.....Anak........🏃`")
    await typew.edit("`🏃................🏃`")
    await typew.edit("`🏃....Ngentot....🏃`")
    await typew.edit("`🏃..............🏃`")
    await typew.edit("`🏃.............🏃`")
    await typew.edit("`🏃..Bodoamat..🏃`")
    await typew.edit("`🏃...........🏃`")
    await typew.edit("`🏃..........🏃`")
    await typew.edit("`🏃.........🏃`")
    await typew.edit("__KOK MAKIN DEKET SI .")
    sleep(1)
    await typew.edit("`🏃.......🏃`")
    await typew.edit("`🏃...Y..🏃`")
    await typew.edit("`🏃.....🏃`")
    await typew.edit("`🏃....🏃`")
    await typew.edit("**Untung Ngga Kena Njir**")
    sleep(1)
    await typew.edit("__Cape Juga Asu Cringe Gitu__")
    sleep(2)
    await typew.edit("**Kasian Si Wibu Wokwokwok**")

@register(outgoing=True, pattern='^.geez(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**Kekuatan Mengjadi Ganteng**")
    await typew.edit("**Kekuatan Menjadi Ganteng Telah Aktif**")
    sleep(3)
    await typew.edit("**Rajin Sholat☑️**")
    await typew.edit("**Rajin Sholat✅**")
    sleep(2)
    await typew.edit("**Tidak Bolos Sekolah☑️**")
    await typew.edit("**Tidak Bolos Sekolah✅**")
    sleep(2)
    await typew.edit("**Gak Sangean☑️**")
    await typew.edit("**Gak Sangean✅**")
    sleep(2)
    await typew.edit("**Harus Sangean☑️**")
    await typew.edit("**Harus Sangean✅**")
    sleep(2)
    await typew.edit("**Tidak Alay☑️**")
    await typew.edit("**Tidak Alay✅**")
    sleep(2)
    await typew.edit("**Suka Membantu☑️**")
    await typew.edit("**Suka Membantu✅**")
    sleep(2)
    await typew.edit("**Selalu Berbagi Duit:v☑️**")
    await typew.edit("**Selaly Berbagi Duit:v✅**")
    sleep(2)
    await typew.edit("**Sukses Menjadi Ganteng**")
    sleep(1)
    await typew.edit("**Iya Ganteng, Seperti Skyzo😎**")


CMD_HELP.update(
    {
        "menggabut": "**✘Plugin :** ` Ga Banyak Sih`\
        \n\n  •  **🐲Perintah :** `.wibuu`\
        \n  •  **💠Function : **__Menghina Wibu Xixixi__\
        \n\n  •  **🐲Perintah : ** `.wibu`\
        \n  •  **💠Function : **__Wibu Kena Mental__\
        \n\n  •  **🐲Perintah :** `.wibbu`\
        \n  •  **💠Function : **__Lari Ada Wibu Global__\
        \n\n  •  **🐲Perintah :** `.geez`\
        \n  •  **💠Function : **__Mengjadi Ganteng__\
    "
    }
)
